openapi: 3.0.0
info:
  title: Sample1 HelloWorld
  version: 1.0.0
  description: Demo microservice for the micro platform
  contact:
    name: igbluz
    email: igbluz@gmail.com
servers:
- url: http://localhost:9080 

paths:
  /helloworld/{message}: 
    get:
      operationId: sayHelloworld
      description: get some greeting
      parameters:
      - name: message
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: greeting from helloworld
          content:
            application/json:
              schema:
                type: string        
